### ISSUE TITLE
Questions about package versions

### ISSUE THREAD

**Issue by xmlyqing00** [songtaohe/LaneExtraction#8]
Hi,

Thanks for providing such great source code and dataset. I would like to train your model but found that it's a little bit hard to create an environment.

I used Conda to create a virtual environment with python==3.5.2 and installed the tensorflow==1.15.0. But I found that it has some import errors:
> Traceback (most recent call last):
  File "train.py", line 2, in <module>
    from model import LaneModel
  File "/mnt/c/Users/yonliang/Sources/LaneExtraction/code/laneAndDirectionExtraction/model.py", line 7, in <module>
    from cnnmodels.resnet34unet import resnet34unet_v3, unet, unet_dilated
  File "/mnt/c/Users/yonliang/Sources/LaneExtraction/code/cnnmodels/resnet34unet.py", line 13, in <module>
    from resnet import resblock as residual_block
  File "/home/lyq/miniconda3/envs/tf/lib/python3.5/site-packages/resnet/__init__.py", line 2, in <module>
    from .resnet152 import ResNet152
  File "/home/lyq/miniconda3/envs/tf/lib/python3.5/site-packages/resnet/resnet152.py", line 27, in <module>
    from keras.applications.imagenet_utils import _obtain_input_shape
ImportError: cannot import name '_obtain_input_shape'

Could you provide a requirements.txt file that we can follow? 

Thanks,
Yongqing

**Comment by a4andromeda** [comment]
Better late than never but i use this based on the tensorflow 1.15 docker container

```
absl-py==0.10.0
astor==0.8.1
cycler==0.11.0
gast==0.2.2
google-pasta==0.2.0
grpcio==1.32.0
h5py==2.10.0
importlib-metadata==2.0.0
Keras-Applications==1.0.8
Keras-Preprocessing==1.1.2
kiwisolver==1.3.1
Markdown==3.2.2
matplotlib==3.3.4
numpy==1.18.5
opencv-python-headless==4.6.0.66
opt-einsum==3.3.0
Pillow==8.4.0
protobuf==3.13.0
PyGObject==3.26.1
pyparsing==3.0.9
python-apt==1.6.5+ubuntu0.3
python-dateutil==2.8.2
scipy==1.1.0
six==1.16.0
tensorboard==1.15.0
tensorflow-estimator==1.15.1
tensorflow-gpu==1.15.4
termcolor==1.1.0
tflearn==0.5.0
Werkzeug==1.0.1
wrapt==1.12.1
zipp==3.2.0
```

**Comment by kevjamco** [comment]
@a4andromeda Thanks for sharing, do you think you can point to the docker container that you used?

**Comment by a4andromeda** [comment]
@kevjamco  I used this one tensorflow/tensorflow:1.15.4-gpu 

To be honest, i got the code running in the end, but it did not led to a meaningful training results

**Comment by GoroYeh-HRI** [comment]
@a4andromeda  Are you using python3 or python2 to run the training script?
Thank you for your sharing!

**Comment by a4andromeda** [comment]
@GoroYeh-HRI  Although i don't remember from back then , the above-mentioned docker container now contains python 3.6.9 and was updated 3 years ago, so i assume that must be the version i  used.
Good luck

**Comment by GoroYeh-HRI** [comment]
@a4andromeda  thanks! You mean you are using Python 3.6.9 to train all 3 models? lanelinesAndDirections, turningLaneExtraction, and turningLaneValidation?

When I use python3, I can train the first two but got "dict_key" object does not support issue.
![image](https://github.com/songtaohe/LaneExtraction/assets/137837175/70c0bca5-7f27-4a22-8e62-07df1c4c76fd)

**Comment by a4andromeda** [comment]
Never got to the third model. The first one never gave me proper results.

**Comment by GoroYeh-HRI** [comment]
@a4andromeda  Got it. Thank you!
May I ask how did you run the inference for first model and found the performance is bad?
Did you only judge it from the training loss?
Thank you.

**Comment by a4andromeda** [comment]
> May I ask how did you run the inference for first model and found the performance is bad?
> Did you only judge it from the training loss?

As far as i remember, the test-time masks were simply empty. Do you think i should revisit it ?
